In [80]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [82]:
df = pd.read_csv('Retail Sales Data Set.csv')

In [84]:
df.head()

,Transaction ID,Date,Gender,Age,Age Group,Product Category,Quantity,Price per Unit,Total Amount,Unnamed: 9,...,Unnamed: 14,Unnamed: 15,Unnamed: 16,Min_age,Max_age,Avg_age,Total Sales Revenue,Average Order value,Category,Sales
0,1,11/24/2023,Male,34,Middle Age,Beauty,3,50,150,NaN,...,NaN,NaN,NaN,18.0,64.0,41.0,456000.0,456.0,Electronics,156905.0
1,2,2/27/2023,Female,26,Adolescent,Clothing,2,500,1000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Clothing,155580.0
2,3,1/13/2023,Male,50,Middle Age,Electronics,1,30,30,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Beauty,143515.0
3,4,5/21/2023,Male,37,Middle Age,Clothing,1,500,500,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,5/6/2023,Male,30,Adolescent,Beauty,2,50,100,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [86]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 24 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Transaction ID       1000 non-null   int64
 1   Date                 1000 non-null   object
 2   Gender               1000 non-null   object
 3   Age                  1000 non-null   int64
 4   Age Group            1000 non-null   object
 5   Product Category     1000 non-null   object
 6   Quantity             1000 non-null   int64
 7   Price per Unit       1000 non-null   int64
 8   Total Amount         1000 non-null   int64
 9   Unnamed: 9           0 non-null      float64
 10  Unnamed: 10          0 non-null      float64
 11  Unnamed: 11          0 non-null      float64
 12  Unnamed: 12          0 non-null      float64
 13  Unnamed: 13          0 non-null      float64
 14  Unnamed: 14          0 non-null      float64
 15  Unnamed: 15          0 non-null      float64
 16  Unnamed: 16          0 non-null      float64
 17  Min_age              1 non-null      float64
 18  Max_age              1 non-null      float64
 19  Avg_age              1 non-null      float64
 20  Total Sales Revenue  1 non-null      float64
 21  Average Order value  1 non-null      float64
 22   Category            3 non-null      object
 23  Sales                3 non-null      float64
dtypes: float64(14), int64(5), object(5)
memory usage: 187.6+ KB

In [88]:
df.isnull().sum().sum()

14989

In [90]:
df.columns

Index(['Transaction ID', 'Date', 'Gender', 'Age', 'Age Group',
       'Product Category', 'Quantity', 'Price per Unit', 'Total Amount',
       'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12',
       'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Min_age',
       'Max_age', 'Avg_age', 'Total Sales Revenue', 'Average Order value',
       ' Category', 'Sales'],
      dtype='object')

In [92]:
uncolumns = [['Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12',
       'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Min_age',
       'Max_age', 'Avg_age', 'Total Sales Revenue', 'Average Order value',
       ' Category', 'Sales']]

In [109]:
df.drop('Unnamed: 9' ,axis =1 , inplace = True)
df.drop('Unnamed: 14' ,axis =1 , inplace = True)
df.drop('Unnamed: 15' ,axis =1 , inplace = True)
df.drop('Min_age' ,axis =1 , inplace = True)

In [111]:
df

,Transaction ID,Date,Gender,Age,Age Group,Product Category,Quantity,Price per Unit,Total Amount,Max_age,Avg_age,Total Sales Revenue,Average Order value,Category,Sales
0,1,11/24/2023,Male,34,Middle Age,Beauty,3,50,150,64.0,41.0,456000.0,456.0,Electronics,156905.0
1,2,2/27/2023,Female,26,Adolescent,Clothing,2,500,1000,NaN,NaN,NaN,NaN,Clothing,155580.0
2,3,1/13/2023,Male,50,Middle Age,Electronics,1,30,30,NaN,NaN,NaN,NaN,Beauty,143515.0
3,4,5/21/2023,Male,37,Middle Age,Clothing,1,500,500,NaN,NaN,NaN,NaN,NaN,NaN
4,5,5/6/2023,Male,30,Adolescent,Beauty,2,50,100,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,5/16/2023,Male,62,Old,Clothing,1,50,50,NaN,NaN,NaN,NaN,NaN,NaN
996,997,11/17/2023,Male,52,Middle Age,Beauty,3,30,90,NaN,NaN,NaN,NaN,NaN,NaN
997,998,10/29/2023,Female,23,Adolescent,Beauty,4,25,100,NaN,NaN,NaN,NaN,NaN,NaN
998,999,12/5/2023,Female,36,Middle Age,Electronics,3,50,150,NaN,NaN,NaN,NaN,NaN,NaN
999,1000,4/12/2023,Male,47,Middle Age,Electronics,4,30,120,NaN,NaN,NaN,NaN,NaN,NaN